# Generated by Django 4.2.5 on 2023-09-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='count',
        ),
    ]
