# Generated by Django 4.2.4 on 2023-10-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_user_notification_recipient_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="action_comment",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.comment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="action_post",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="base.post",
            ),
            preserve_default=False,
        ),
    ]
